/*
  shared include file for definition of the communication between light and main node...

  the light protocol needs to be placed in the arduino sketch path in order for it to work
  the light_protocol.h in here is just a placeholder and wrapper...
*/

#include "../src/light_node/light_protocol.h"

// no declarations here...
// at least not anything that is used on the arduino end...
